In [1]:
import torch
import torch.nn as nn

from torch import distributions

Discrete

In [2]:
test_logits = torch.randn(4, 4)
test_dist = distributions.Categorical(logits=test_logits)
test_dist

Categorical(logits: torch.Size([4, 4]))

In [5]:
def test():
    sample0, sample1 = [test_dist.sample() for _ in range(2)]
    log_prob0, log_prob1 = [test_dist.log_prob(s) for s in (sample0, sample1)]
    log_prob2 = test_dist.log_prob(sample0)
    return sample0, sample1, log_prob0, log_prob1, log_prob2

test()

(tensor([2, 0, 3, 0]),
 tensor([2, 0, 2, 1]),
 tensor([-0.6769, -1.0806, -1.8013, -1.1730]),
 tensor([-0.6769, -1.0806, -0.7254, -0.8063]),
 tensor([-0.6769, -1.0806, -1.8013, -1.1730]))

In [6]:
test_mean, _test_std = torch.randn(4, 8).chunk(2, -1)
test_std = torch.abs(_test_std)
test_dist = distributions.Normal(test_mean, test_std)
test_dist, test()

(Normal(loc: torch.Size([4, 4]), scale: torch.Size([4, 4])),
 (tensor([[ 0.1228,  1.5435, -3.8671,  0.1075],
          [ 0.5496,  0.6838, -0.0062, -0.5747],
          [-0.6695, -0.4827, -0.4657,  1.6798],
          [-1.5863,  0.9864,  0.6179, -0.2556]]),
  tensor([[-0.6820,  1.5482, -0.8662, -0.1933],
          [ 0.6490,  0.6131, -0.2823, -0.6260],
          [-0.1533, -0.3770, -0.5344,  0.9983],
          [-0.8232,  1.2823,  0.5338, -0.5844]]),
  tensor([[-1.3084e+00,  3.0966e+00, -2.2175e+00, -5.7174e-01],
          [ 1.4607e+00,  2.2770e+00, -9.3272e-01,  2.2552e-03],
          [-1.0040e-01,  1.7506e+00, -9.7921e-02, -1.9462e-01],
          [-4.0327e-01,  6.3914e-01,  1.0879e+00,  6.4652e-01]]),
  tensor([[-1.2182,  3.0902, -1.5476, -0.9584],
          [ 1.3118,  1.1549, -1.3302,  0.0436],
          [-0.1898,  1.1978,  0.2575, -0.7222],
          [-0.5106, -0.0752,  1.4115, -0.0380]]),
  tensor([[-1.3084e+00,  3.0966e+00, -2.2175e+00, -5.7174e-01],
          [ 1.4607e+00,  2.2770e+00

In [17]:
test_mean, _test_std = torch.randn(4, 8).chunk(2, -1)
test_std = torch.abs(_test_std).diag_embed()
test_dist = distributions.MultivariateNormal(test_mean, scale_tril=test_std)
test_dist, test()

(MultivariateNormal(loc: torch.Size([4, 4]), scale_tril: torch.Size([4, 4, 4])),
 (tensor([[-0.6386,  1.8641, -0.3492, -3.0052],
          [-0.4636,  0.2492,  4.5482, -0.8877],
          [-0.1360,  1.0811,  0.4763, -0.3666],
          [ 4.6122,  1.6170, -1.0825,  0.8681]]),
  tensor([[-0.3678,  2.2973,  0.2633, -0.8908],
          [ 0.3243, -0.4456,  3.1817, -1.8976],
          [ 0.3579,  1.3292,  2.8437,  0.1213],
          [ 1.3266,  1.7952, -0.5267,  1.1568]]),
  tensor([-3.6750, -5.2130, -4.3501, -4.9978]),
  tensor([-4.0939, -3.6874, -2.9542, -1.0962]),
  tensor([-3.6750, -5.2130, -4.3501, -4.9978])))