In [1]:
from ModifiedNEAT.nn.modules.base import *
from ModifiedNEAT import Genome

import torch

In [2]:
torch.set_printoptions(threshold=10)

In [3]:
device = 'cuda'

In [4]:
genomes = {key: Genome(key) for key in range(1, 2)}

In [5]:
batch_size = 5
seq_len = 32
input_dims = 8
output_dims = 16
heads = 4

In [6]:
linear = Linear(input_dims, output_dims, True, device)
linear.update(genomes)
linear, linear.weights.shape

(Linear[NeatModule](inputs=8, outputs=16, bias=True), torch.Size([1, 8, 16]))

In [7]:
inputs = torch.randn(len(genomes), batch_size, seq_len, input_dims, device=device)
inputs.shape

torch.Size([1, 5, 32, 8])

In [8]:
linear.weights.data, linear.biases.data

(Parameter containing:
 tensor([[[ 1.0807, -0.9631, -2.1196,  ...,  1.4182, -0.8461,  1.1465],
          [-1.9189,  1.5109,  1.6987,  ...,  0.8379, -0.5175,  0.1560],
          [ 1.9771, -1.0465,  0.1242,  ...,  0.3064, -0.3610,  1.5324],
          ...,
          [ 0.8178, -0.2970,  2.7186,  ...,  0.4076,  0.2083, -0.7641],
          [-1.2234, -0.6987,  0.8481,  ...,  0.1517,  0.3510,  0.7169],
          [-0.4604, -0.1771, -0.9620,  ...,  1.4083, -1.5187, -0.3057]]],
        device='cuda:0'),
 Parameter containing:
 tensor([[ 0.3692,  0.7084,  2.5624,  ..., -0.0302,  1.4947, -1.1201]],
        device='cuda:0'))

In [9]:
inputs, inputs.shape

(tensor([[[[-0.9063,  0.2562,  1.5059,  ...,  1.2022, -0.7071,  0.2598],
           [-1.1097,  1.4972, -0.1669,  ...,  0.0856, -0.3410, -1.8543],
           [-0.3993,  0.8636, -0.3471,  ..., -0.3164, -0.6159, -1.0654],
           ...,
           [-1.0044,  0.6692,  1.5517,  ..., -0.6891,  0.3479,  1.3337],
           [-0.2057, -0.0985,  1.0139,  ...,  0.1499, -0.1722,  0.5904],
           [ 0.4338,  1.1901, -1.7558,  ..., -0.1402,  2.2161, -0.7649]],
 
          [[-0.6727,  1.1050, -2.0247,  ...,  1.8281, -0.7439, -0.2523],
           [-1.5404, -0.1261,  2.7493,  ...,  1.4511, -1.6583,  0.4771],
           [ 1.1938, -0.5154,  0.4691,  ..., -1.5483, -1.3506,  0.0704],
           ...,
           [ 0.7541,  0.7306,  0.1121,  ..., -0.0509, -0.0372,  2.1127],
           [-0.6931, -0.0346, -1.5186,  ..., -0.4422,  0.5485, -0.4294],
           [-0.4559, -0.0612, -0.1867,  ...,  0.1667,  0.5716,  0.0635]],
 
          [[-0.9995, -1.5347, -0.5776,  ...,  0.1579, -2.5208,  1.3624],
           [-

In [10]:
inputs.shape

torch.Size([1, 5, 32, 8])

In [11]:
# %%timeit -r 10   -n 10
outputs = linear(inputs)
outputs.shape

torch.Size([1, 5, 32, 16])

In [12]:
outputs

tensor([[[[ -0.2355,   0.2103,   3.5090,  ...,  -0.2968,   0.8147,  -1.1778],
          [ -3.1815,   4.8320,   8.8834,  ...,  -3.2026,   4.4683,  -2.8291],
          [ -2.0103,   3.6905,   4.3925,  ...,  -2.0467,   2.9812,  -3.4236],
          ...,
          [ -2.3605,   0.8327,   1.6117,  ...,   0.8483,  -0.6589,  -0.4320],
          [  2.8038,  -0.1391,   3.4111,  ...,   0.6354,   0.5899,  -1.2669],
          [ -7.4949,   2.8019,   6.0978,  ...,  -0.0430,   3.2351,  -2.7658]],

         [[ -4.5001,   5.6573,  10.7255,  ...,  -1.0372,   3.0668,  -9.9258],
          [  4.3810,  -0.5180,   4.7510,  ...,  -0.7044,   0.5176,  -0.5820],
          [  3.0889,  -0.1790,  -6.6712,  ...,   0.3295,  -0.2546,  -0.1302],
          ...,
          [ -0.2146,   0.2444,  -0.1183,  ...,   5.2000,  -3.0513,   2.1169],
          [ -4.4670,   3.8543,   5.4867,  ...,  -3.4880,   4.2173, -10.4152],
          [  1.6553,   0.5962,   6.2336,  ...,   0.1518,   2.0933,   0.5810]],

         [[  2.2216,   1.5149,

In [13]:
linear(inputs[0], keys=1)

tensor([[[ -0.2355,   0.2103,   3.5090,  ...,  -0.2968,   0.8147,  -1.1778],
         [ -3.1815,   4.8320,   8.8834,  ...,  -3.2026,   4.4683,  -2.8291],
         [ -2.0103,   3.6905,   4.3925,  ...,  -2.0467,   2.9812,  -3.4236],
         ...,
         [ -2.3605,   0.8327,   1.6117,  ...,   0.8483,  -0.6589,  -0.4320],
         [  2.8038,  -0.1391,   3.4111,  ...,   0.6354,   0.5899,  -1.2669],
         [ -7.4949,   2.8019,   6.0978,  ...,  -0.0430,   3.2351,  -2.7658]],

        [[ -4.5001,   5.6573,  10.7255,  ...,  -1.0372,   3.0668,  -9.9258],
         [  4.3810,  -0.5180,   4.7510,  ...,  -0.7044,   0.5176,  -0.5820],
         [  3.0889,  -0.1790,  -6.6712,  ...,   0.3295,  -0.2546,  -0.1302],
         ...,
         [ -0.2146,   0.2444,  -0.1183,  ...,   5.2000,  -3.0513,   2.1169],
         [ -4.4670,   3.8543,   5.4867,  ...,  -3.4880,   4.2173, -10.4152],
         [  1.6553,   0.5962,   6.2336,  ...,   0.1518,   2.0933,   0.5810]],

        [[  2.2216,   1.5149,  -2.1497,  ...

# Working Principle - Norm

In [14]:
affine = True

In [15]:
norm = LayerNorm((output_dims,), elementwise_affine=affine, bias=True, device=device)
norm.update(genomes)
norm

LayerNorm[NeatModule](shape=(16,), eps=1e-08, elementwise_affine=True, bias=True)

In [16]:
norm(outputs).shape

torch.Size([1, 5, 32, 16])

In [17]:
group_norm = GroupNorm(heads, output_dims, affine=affine, bias=True, device=device)
group_norm.update(genomes)
group_norm

GroupNorm[NeatModule](groups=4, channels=16, eps=1e-06, affine=True, bias=True)

In [18]:
group_norm(outputs.mT).mT.shape

torch.Size([1, 5, 32, 16])

In [19]:
rms_norm = RMSNorm(output_dims, elementwise_affine=affine, device=device)
rms_norm.update(genomes)
rms_norm

RMSNorm[NeatModule](shape=(16,), eps=1e-08, elementwise_affine=True)

In [20]:
rms_norm(outputs).shape

torch.Size([1, 5, 32, 16])

Timings

In [21]:
%%timeit -r 100 -n 5
norm(outputs);

269 μs ± 57.8 μs per loop (mean ± std. dev. of 100 runs, 5 loops each)


In [22]:
%%timeit -r 100 -n 5
group_norm(outputs.mT).mT;

The slowest run took 4.12 times longer than the fastest. This could mean that an intermediate result is being cached.
328 μs ± 140 μs per loop (mean ± std. dev. of 100 runs, 5 loops each)


In [23]:
%%timeit -r 100 -n 5
rms_norm(outputs);

The slowest run took 4.04 times longer than the fastest. This could mean that an intermediate result is being cached.
218 μs ± 85.1 μs per loop (mean ± std. dev. of 100 runs, 5 loops each)
