In [10]:
from numba import njit
import numpy as np
import math

In [13]:
np.inf + 1, -np.finfo(np.float32).max.item()

(inf, -3.4028234663852886e+38)

In [3]:
test_shape = (3, 3, 3)
test_array = np.arange(math.prod(test_shape), dtype=int).reshape(test_shape)
test_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [4]:
test_mask0 = np.random.randint(0, 2, test_shape).astype(bool)
test_mask0

array([[[ True, False,  True],
        [ True,  True,  True],
        [False, False,  True]],

       [[ True,  True,  True],
        [ True, False,  True],
        [False, False, False]],

       [[ True,  True,  True],
        [False, False, False],
        [ True, False, False]]])

In [6]:
test_mask1 = np.random.randint(0, 2, test_shape[0]).astype(bool)
test_mask1

array([False, False,  True])

In [8]:
test_mask1[:, None, None] & test_mask0

array([[[False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False]],

       [[ True,  True,  True],
        [False, False, False],
        [ True, False, False]]])

In [10]:
test_mask1[:, None, None].shape

(3, 1, 1)

In [13]:
players, length, width = 3, 3, 3
mask = np.random.rand(players, length, width) > 0.5  # random True/False
mask.astype(int)

array([[[0, 0, 1],
        [1, 1, 0],
        [0, 0, 0]],

       [[0, 1, 0],
        [1, 0, 0],
        [1, 0, 0]],

       [[1, 1, 1],
        [1, 0, 1],
        [1, 0, 0]]])

In [15]:
coords = []

for p in range(players):
    # Get indices where mask is True for this player
    ys, xs = np.where(mask[p])

    if len(xs) == 0:
        # no available positions
        coords.append(None)
    else:
        # pick a random available index
        i = np.random.randint(len(xs))
        coords.append((ys[i].item(), xs[i].item()))
coords

[(0, 2), (0, 1), (0, 2)]

In [17]:
fill = np.full_like(mask, False, bool)
for i, pos, in enumerate(coords):
    if pos is None:
        continue
    else:
        x, y = pos
        fill[i, x, y] = True
fill.astype(int)

array([[[0, 0, 1],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 1, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 1],
        [0, 0, 0],
        [0, 0, 0]]])

In [20]:
math.cos(0.5 * math.pi * 1), math.sin(0.5 * math.pi * 1)

(6.123233995736766e-17, 1.0)

In [21]:
np.cos(0.5 * math.pi * 1), np.sin(0.5 * math.pi * 1)

(np.float64(6.123233995736766e-17), np.float64(1.0))

In [23]:
position = (10, 15)
position + (1, 0)

(10, 15, 1, 0)

In [1]:
import torch
import torch.nn as nn
from torch import distributions

In [2]:
test_tensor = torch.randn((3, 1, 3))

In [3]:
test_dist = distributions.Categorical(probs=torch.softmax(test_tensor, -1))
test_dist.sample()

tensor([[1],
        [1],
        [0]])

In [9]:
nn.AdaptiveAvgPool1d(3)(torch.randn((3, 1, 128))).shape

torch.Size([3, 1, 3])